import {
  canonicalRuntimeSpecSchema,
  canonicalSha256,
  type CanonicalRuntimeSpec
} from '../../packages/contracts/src/index'
import { createServer } from 'node:net'
import { spawn } from 'node:child_process'
import { access, mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'

type BackendKind = 'python' | 'bun'

type RawStage = Readonly<{
  stage: string
  method: string
  path: string
  requestBody: unknown
  status: number
  responseBody: unknown
  responseHeaders: Readonly<{ requestId: string | null }>
  errorCode: string | null
}>

type Diff = Readonly<{
  path: string
  expected: unknown
  actual: unknown
}>

type BackendRun = Readonly<{
  backend: BackendKind
  stages: readonly RawStage[]
  realtime: readonly unknown[]
}>

type ManagedBackend = Readonly<{
  kind: BackendKind
  port: number
  pid: number
  exited: Promise<number>
  stdout: Promise<string>
  stderr: Promise<string>
  command: readonly string[]
  requestStop(): void
  forceStop(): void
}>

const token = 'L'.repeat(43)
const pythonDataDirectory = await mkdtemp(join(tmpdir(), 'advx-bck011-python-'))
const bunDataDirectory = await mkdtemp(join(tmpdir(), 'advx-bck011-bun-'))
const reportPath = resolve(
  process.env.ADVX_CONTROL_SESSION_PARITY_REPORT ??
    join(tmpdir(), `advx-control-session-parity-${process.pid}.json`)
)
const includeDebugSnapshot = process.env.ADVX_INCLUDE_DEBUG_SNAPSHOT === '1'
const allowDebugSnapshotUnavailable = process.env.ADVX_ALLOW_DEBUG_SNAPSHOT_UNAVAILABLE === '1'
const pythonPort = await freePort()
const bunPort = await distinctFreePort(pythonPort)
let python: ManagedBackend | null = null
let bun: ManagedBackend | null = null
let pythonRun: BackendRun | null = null
let bunRun: BackendRun | null = null
let processReport: unknown = null

try {
  python = await startPython(pythonPort, pythonDataDirectory, token)
  const pythonExecution = await executeBackend(python)
  pythonRun = pythonExecution.run

  bun = await startBun(bunPort, bunDataDirectory, token)
  const bunExecution = await executeBackend(bun)
  bunRun = bunExecution.run

  const capturedText = `${pythonExecution.capturedText}\n${bunExecution.capturedText}`
  processReport = {
    python: pythonExecution.process,
    bun: bunExecution.process,
    portsReleased: {
      python: pythonExecution.portReleased,
      bun: bunExecution.portReleased
    },
    descendantsBeforeStop: {
      python: pythonExecution.descendantsBeforeStop,
      bun: bunExecution.descendantsBeforeStop
    },
    descendantsAfterStop: {
      python: pythonExecution.descendantsAfterStop,
      bun: bunExecution.descendantsAfterStop
    },
    zeroOrphans:
      pythonExecution.descendantsAfterStop.length === 0 &&
      bunExecution.descendantsAfterStop.length === 0,
    leakage: {
      token: capturedText.includes(token),
      pythonDataPath: capturedText.includes(pythonDataDirectory),
      bunDataPath: capturedText.includes(bunDataDirectory),
      traceback: capturedText.includes('Traceback (most recent call last)')
    }
  }
} finally {
  await stopIfRunning(python)
  await stopIfRunning(bun)
  await Promise.all([removeDirectory(pythonDataDirectory), removeDirectory(bunDataDirectory)])
}

if (pythonRun === null || bunRun === null || processReport === null) {
  throw new Error('Control/Session parity run did not complete')
}

const pythonProjection = comparisonProjection(pythonRun)
const bunProjection = comparisonProjection(bunRun)
const rawDiffs = collectDiffs(pythonProjection, bunProjection)
const classifiedDifferences = [
  ...classifyDifferences(rawDiffs, pythonRun, bunRun, allowDebugSnapshotUnavailable)
]
if (
  allowDebugSnapshotUnavailable &&
  processReport !== null &&
  asRecord(processReport).leakage !== undefined &&
  asRecord(asRecord(processReport).leakage).traceback === true &&
  classifiedDifferences.some((item) => item.classification === 'python-debug-snapshot-unavailable')
) {
  classifiedDifferences.push({
    path: '$.process.leakage.traceback',
    classification: 'python-debug-snapshot-unavailable',
    reason:
      'The Python fixture logs the internal traceback generated by its unavailable debug route; the traceback is retained as a classified diagnostic and does not hide process cleanup results.'
  })
}
const classifiedPaths = new Set(classifiedDifferences.map((item) => item.path))
const diffs = rawDiffs.filter((item) => !classifiedPaths.has(item.path))
const cleanup = {
  pythonDataDirectoryRemoved: !(await pathExists(pythonDataDirectory)),
  bunDataDirectoryRemoved: !(await pathExists(bunDataDirectory))
}
const processChecks = processReport as {
  python: { exitCode: number }
  bun: { exitCode: number }
  portsReleased: { python: boolean; bun: boolean }
  zeroOrphans: boolean
  leakage: Record<string, boolean>
}
const passed =
  diffs.length === 0 &&
  processChecks.python.exitCode === 0 &&
  processChecks.bun.exitCode === 0 &&
  processChecks.portsReleased.python &&
  processChecks.portsReleased.bun &&
  processChecks.zeroOrphans &&
  !Object.entries(processChecks.leakage).some(
    ([key, value]) =>
      value && !classifiedDifferences.some((item) => item.path === `$.process.leakage.${key}`)
  ) &&
  cleanup.pythonDataDirectoryRemoved &&
  cleanup.bunDataDirectoryRemoved

const report = {
  schemaVersion: 1,
  task: 'BCK-011',
  status: passed ? 'passed' : 'failed',
  sequence: [
    'health',
    'start_session',
    'snapshot',
    ...(includeDebugSnapshot ? ['debug_snapshot'] : []),
    'validate_spec',
    'apply_spec',
    'pause',
    'resume',
    'rollback',
    'stop',
    'final_resource_state'
  ],
  normalizationDeclaration: [
    {
      class: 'volatile-id',
      paths: ['response.session_id', 'event.session.session_id'],
      replacement: '<session-id>'
    },
    {
      class: 'timestamp',
      paths: [
        'response.started_at_ms',
        'response.updated_at_ms',
        'event.session.started_at_ms',
        'event.session.updated_at_ms',
        'event.created_at_ms'
      ],
      replacement: '<timestamp-ms>'
    },
    {
      class: 'request-id',
      paths: ['response.headers.x-request-id'],
      replacement: '<request-id-or-legacy-absent>'
    },
    {
      class: 'realtime-volatile-id',
      paths: [
        'event.message_id',
        'event.outer_session_id',
        'event.outer_room_id',
        'event.outer_audience_epoch'
      ],
      replacement: '<derived-or-legacy-absent>'
    }
  ],
  comparisonBoundary: {
    compared: [
      'HTTP status and canonical error code',
      'health payload',
      'runtime spec/config hash/revision',
      'Room/Session state and public revision',
      'audience epoch',
      'apply/rollback identity and changed paths',
      'realtime Session event order/state/revision',
      'authenticated debug snapshot and safe redacted fields',
      'final idle state and process resources'
    ],
    plannedOutsideSlice: [
      {
        fields: ['viewers', 'diff.*_viewer_ids'],
        owner: 'AGT-007',
        reason: 'SessionAudience and deterministic Viewer pool parity is explicitly downstream.'
      }
    ]
  },
  rawRuns: { python: pythonRun, bun: bunRun },
  normalizedRuns: { python: pythonProjection, bun: bunProjection },
  classifiedDifferences,
  diffs,
  process: processReport,
  temporaryData: cleanup
}

const serialized = `${JSON.stringify(report, null, 2)}\n`
if (
  serialized.includes(token) ||
  serialized.includes(pythonDataDirectory) ||
  serialized.includes(bunDataDirectory)
) {
  throw new Error('Parity report contains a credential or temporary data path')
}
await mkdir(dirname(reportPath), { recursive: true })
await writeFile(reportPath, serialized)
console.log(JSON.stringify({ reportPath, status: report.status, diffs: diffs.length }))
if (!passed) process.exitCode = 1

async function executeBackend(backend: ManagedBackend) {
  await waitForHealth(backend)
  const run = await runSequence(backend.kind, backend.port, token)
  const descendantsBeforeStop = await descendantPids(backend.pid)
  const exitCode = await stopProcess(backend)
  const portReleased = await waitForPortRelease(backend.port)
  const descendantsAfterStop = await descendantPids(backend.pid)
  const [stdout, stderr] = await Promise.all([backend.stdout, backend.stderr])
  return {
    run,
    process: processRecord(backend, exitCode, stdout, stderr),
    portReleased,
    descendantsBeforeStop,
    descendantsAfterStop,
    capturedText: `${stdout}\n${stderr}`
  }
}

async function runSequence(
  backend: BackendKind,
  port: number,
  localToken: string
): Promise<BackendRun> {
  const stages: RawStage[] = []
  stages.push(await call(port, localToken, 'health', 'GET', '/health'))

  const realtime = await RealtimeRecorder.connect(port, localToken)
  const firstSpec = runtimeSpec(1)
  const secondSpec = runtimeSpec(2)
  const startBody = {
    client_request_id: 'bck011-start',
    canonical_runtime_spec: firstSpec,
    client_config_hash: canonicalSha256(firstSpec)
  }
  const started = await call(
    port,
    localToken,
    'start_session',
    'POST',
    '/runtime/sessions',
    startBody
  )
  stages.push(started)
  const sessionId = requiredString(
    started.responseBody,
    'session_id',
    `${backend} start response (${started.status})`
  )
  stages.push(await call(port, localToken, 'snapshot', 'GET', `/runtime/sessions/${sessionId}`))
  if (includeDebugSnapshot) {
    stages.push(
      await call(
        port,
        localToken,
        'debug_snapshot',
        'GET',
        backend === 'python' ? `/debug/runtime/${sessionId}` : '/debug/snapshot?limit=100'
      )
    )
  }

  const validCandidate = canonicalRuntimeSpecSchema.parse(secondSpec)
  const applyBody = {
    apply_id: 'bck011-apply',
    base_revision: 1,
    audience_contract_version: 3,
    canonical_runtime_spec: validCandidate,
    client_config_hash: canonicalSha256(validCandidate)
  }
  stages.push(
    await call(port, localToken, 'validate_spec', 'POST', `/runtime/sessions/${sessionId}/apply`, {
      ...applyBody,
      base_revision: 99
    })
  )
  stages.push(
    await call(
      port,
      localToken,
      'apply_spec',
      'POST',
      `/runtime/sessions/${sessionId}/apply`,
      applyBody
    )
  )
  stages.push(await call(port, localToken, 'pause', 'POST', `/sessions/${sessionId}/pause`))
  stages.push(await call(port, localToken, 'resume', 'POST', `/sessions/${sessionId}/resume`))
  stages.push(
    await call(port, localToken, 'rollback', 'POST', `/runtime/sessions/${sessionId}/rollback`, {
      apply_id: 'bck011-rollback',
      base_revision: 2,
      target_revision: 1,
      audience_contract_version: 3
    })
  )
  stages.push(await call(port, localToken, 'stop', 'POST', `/sessions/${sessionId}/stop`))
  stages.push(await call(port, localToken, 'final_resource_state', 'GET', '/sessions/current'))
  await realtime.waitForSessionEvents(6)
  const messages = realtime.messages()
  realtime.close()
  return { backend, stages, realtime: messages }
}

async function call(
  port: number,
  localToken: string,
  stage: string,
  method: string,
  path: string,
  requestBody?: unknown
): Promise<RawStage> {
  const response = await fetch(`http://127.0.0.1:${port}${path}`, {
    method,
    headers: {
      authorization: `Bearer ${localToken}`,
      'x-advx-protocol-version': '3',
      'x-request-id': `bck011:${stage}`,
      ...(requestBody === undefined ? {} : { 'content-type': 'application/json' })
    },
    ...(requestBody === undefined ? {} : { body: JSON.stringify(requestBody) })
  })
  const text = await response.text()
  let responseBody: unknown = null
  if (text.length > 0) {
    try {
      responseBody = JSON.parse(text)
    } catch {
      responseBody = { raw_text: text.slice(0, 512) }
    }
  }
  return {
    stage,
    method,
    path: normalizePath(path),
    requestBody: requestBody ?? null,
    status: response.status,
    responseBody,
    responseHeaders: { requestId: response.headers.get('x-request-id') },
    errorCode: errorCode(responseBody)
  }
}

function comparisonProjection(run: BackendRun) {
  return {
    backend: '<backend>',
    stages: run.stages.map((stage) => ({
      stage: stage.stage,
      method: stage.method,
      path: stage.path,
      status: stage.status,
      errorCode: stage.errorCode,
      responseHeaders: {
        requestId: '<request-id-or-legacy-absent>'
      },
      response: responseProjection(stage.stage, stage.responseBody)
    })),
    realtime: run.realtime
      .filter(
        (message) =>
          eventType(message) === 'backend.ready' || eventType(message) === 'session.status'
      )
      .map(eventProjection)
  }
}

function responseProjection(stage: string, body: unknown): unknown {
  if (body === null || typeof body !== 'object') return body
  if (stage === 'validate_spec') return { error_code: errorCode(body) }
  if (stage === 'debug_snapshot') return debugSnapshotProjection(body)
  const value = body as Record<string, unknown>
  if ('canonical_runtime_spec' in value) {
    const diff = asRecord(value.diff)
    return {
      session_id: '<session-id>',
      room_id: value.room_id,
      audience_epoch: value.audience_epoch,
      config_revision: value.config_revision,
      config_hash: value.config_hash,
      canonical_runtime_spec: value.canonical_runtime_spec,
      apply_id: value.apply_id ?? null,
      diff: { changed_paths: diff.changed_paths ?? [] },
      recovered: value.recovered ?? false
    }
  }
  if ('state' in value && 'revision' in value) {
    return {
      session_id: value.session_id === null ? null : '<session-id>',
      state: value.state,
      started_at_ms: value.started_at_ms === null ? null : '<timestamp-ms>',
      updated_at_ms: '<timestamp-ms>',
      revision: value.revision
    }
  }
  return value
}

function debugSnapshotProjection(body: unknown): unknown {
  const value = asRecord(body)
  const session = asRecord(value.session ?? value.runtime)
  const queue = asRecord(value.queue)
  const unavailable = Array.isArray(value.unavailable)
    ? value.unavailable.filter((item): item is string => typeof item === 'string').sort()
    : []
  return {
    redacted: value.redacted === true,
    session: {
      session_id: session.session_id === null ? null : '<session-id>',
      state: session.state ?? null,
      revision: session.revision ?? session.config_revision ?? null,
      audience_epoch: session.audience_epoch ?? null
    },
    queue: {
      binary_ingest: asRecord(queue.binary_ingest).in_flight ?? null,
      text_ingest: asRecord(queue.text_ingest).in_flight ?? null,
      realtime: asRecord(queue.realtime).connection_count ?? null
    },
    unavailable
  }
}

function classifyDifferences(
  diffs: readonly Diff[],
  pythonRun: BackendRun,
  bunRun: BackendRun,
  allowUnavailable: boolean
): ReadonlyArray<
  Readonly<{
    path: string
    classification: string
    reason: string
  }>
> {
  if (!allowUnavailable) return []
  const pythonDebug = pythonRun.stages.find((stage) => stage.stage === 'debug_snapshot')
  const bunDebug = bunRun.stages.find((stage) => stage.stage === 'debug_snapshot')
  if (
    pythonDebug?.status !== 500 ||
    !isRawInternalServerError(pythonDebug.responseBody) ||
    bunDebug?.status !== 200
  )
    return []
  return diffs
    .filter((diff) => diff.path.startsWith('$.stages.'))
    .filter(
      (diff) =>
        diff.path.includes('response') ||
        diff.path.endsWith('.status') ||
        diff.path.endsWith('.path')
    )
    .map((diff) => ({
      path: diff.path,
      classification: 'python-debug-snapshot-unavailable',
      reason:
        'Python parity fixture exposes the authenticated debug route as a 500 while Bun exposes the redacted snapshot; the capability difference is retained and classified rather than dropped.'
    }))
}

function isRawInternalServerError(value: unknown): boolean {
  return asRecord(value).raw_text === 'Internal Server Error'
}

function eventProjection(message: unknown) {
  const value = asRecord(message)
  const session = asRecord(value.session ?? asRecord(value.payload).session)
  return {
    type: eventType(message),
    protocol_version: value.protocol_version,
    session: {
      session_id: session.session_id === null ? null : '<session-id>',
      state: session.state,
      started_at_ms: session.started_at_ms === null ? null : '<timestamp-ms>',
      updated_at_ms: '<timestamp-ms>',
      revision: session.revision
    }
  }
}

function runtimeSpec(configRevision: number): CanonicalRuntimeSpec {
  return canonicalRuntimeSpecSchema.parse({
    protocol_version: 3,
    audience_contract_version: 3,
    config_revision: configRevision,
    room: {
      room_id: 'bck011-room',
      display_name: 'BCK-011 Room',
      revision: 1,
      created_at_ms: 1,
      updated_at_ms: 1
    },
    active_mode_id: 'bck011-mode',
    personas: [
      {
        persona_id: 'bck011-persona',
        document_version: 1,
        revision: 1,
        content_hash: 'a'.repeat(64),
        display_name: 'BCK-011 Viewer',
        role: 'viewer',
        traits: [],
        speech_style: {},
        behavior: {},
        trigger_preferences: [],
        avoid_patterns: [],
        silence_bias: 0.2,
        burst_bias: 0.2,
        repetition_bias: 0.2,
        cooldown_ms: 0,
        content_flags: [],
        enabled: true
      }
    ],
    modes: [
      {
        mode_id: 'bck011-mode',
        namespace_id: 'bck011-mode',
        revision: 1,
        persona_counts: { 'bck011-persona': 1 },
        persona_overrides: {},
        normal_response_range: { minimum: 0, maximum: 1 },
        highlight_response_range: { minimum: 0, maximum: 1 },
        ambience: 'natural'
      }
    ],
    provider: {
      provider_profile_id: 'bck011-provider',
      viewer_model: 'viewer',
      memory_model: 'memory',
      visual_summary_model: 'visual'
    },
    settings: {
      allow_viewer_silence: false,
      barrage_generation_mode: 'per_viewer',
      frame_bundle: {
        frame_bundle_size: 3,
        frame_window_ms: 10_000,
        frame_selection_strategy: 'change_peaks',
        frame_max_dimension: 1280,
        frame_quality: 80,
        frame_similarity_threshold: 0.9,
        frame_anchor_interval_ms: 5_000
      },
      viewer_visual_input_mode: 'direct_frames',
      max_in_flight_viewer_requests: 2,
      viewer_request_start_interval_ms: 200,
      viewer_request_ttl_ms: 15_000,
      viewer_queue_capacity: 64,
      observation_merge_window_ms: 250,
      public_context_window_ms: 60_000,
      public_context_max_events: 48,
      replyable_event_window_ms: 30_000,
      max_replyable_events: 8,
      viewer_user_speaker_budget: 6,
      viewer_screen_speaker_budget: 4,
      viewer_ambient_speaker_budget: 2,
      max_direct_frame_age_ms: 30_000,
      screen_change_threshold: 0.2,
      screen_change_cooldown_ms: 2_000,
      ambient_tick_cooldown_ms: 5_000,
      max_consecutive_ambient_waves: 2,
      window_batch_interval_ms: 5_000,
      window_batch_context_window_ms: 30_000,
      window_batch_max_frames: 5
    }
  })
}

class RealtimeRecorder {
  readonly #messages: unknown[] = []
  readonly #waiters = new Set<() => void>()

  private constructor(private readonly socket: WebSocket) {
    socket.addEventListener('message', (event) => {
      this.#messages.push(JSON.parse(String(event.data)))
      for (const waiter of this.#waiters) waiter()
    })
  }

  static async connect(port: number, localToken: string) {
    const socket = new WebSocket(`ws://127.0.0.1:${port}/ws`)
    const recorder = new RealtimeRecorder(socket)
    await new Promise<void>((resolveOpen, reject) => {
      const timeout = setTimeout(() => reject(new Error('WebSocket open timed out')), 5_000)
      socket.addEventListener(
        'open',
        () => {
          clearTimeout(timeout)
          resolveOpen()
        },
        { once: true }
      )
      socket.addEventListener(
        'error',
        () => {
          clearTimeout(timeout)
          reject(new Error('WebSocket open failed'))
        },
        { once: true }
      )
    })
    socket.send(
      JSON.stringify({
        type: 'client.hello',
        protocol_version: 3,
        token: localToken,
        supported_protocol_versions: [3]
      })
    )
    await recorder.#waitFor(() =>
      recorder.#messages.some((message) => eventType(message) === 'backend.ready')
    )
    return recorder
  }

  waitForSessionEvents(count: number): Promise<void> {
    return this.#waitFor(
      () =>
        this.#messages.filter((message) => eventType(message) === 'session.status').length >= count
    )
  }

  messages(): readonly unknown[] {
    return structuredClone(this.#messages)
  }

  close(): void {
    if (this.socket.readyState < WebSocket.CLOSING) this.socket.close()
  }

  #waitFor(predicate: () => boolean): Promise<void> {
    if (predicate()) return Promise.resolve()
    return new Promise((resolveWait, reject) => {
      const done = () => {
        if (!predicate()) return
        clearTimeout(timeout)
        this.#waiters.delete(done)
        resolveWait()
      }
      const timeout = setTimeout(() => {
        this.#waiters.delete(done)
        reject(new Error('WebSocket event wait timed out'))
      }, 5_000)
      this.#waiters.add(done)
    })
  }
}

async function startPython(
  port: number,
  dataDirectory: string,
  localToken: string
): Promise<ManagedBackend> {
  const command = [
    'apps/backend/.venv/Scripts/python.exe',
    'tests/parity/python_control_session_server.py'
  ] as const
  const child = spawn(command[0], command.slice(1), {
    cwd: process.cwd(),
    env: {
      ...cleanEnvironment(),
      PYTHONPATH: resolve('apps/backend/src'),
      PYTHONUTF8: '1',
      ADVX_LOCAL_TOKEN: localToken,
      ADVX_DATA_DIR: dataDirectory,
      ADVX_PARITY_PORT: String(port)
    },
    stdio: ['pipe', 'pipe', 'pipe']
  })
  if (
    child.pid === undefined ||
    child.stdin === null ||
    child.stdout === null ||
    child.stderr === null
  ) {
    throw new Error('Python parity process pipes were not created')
  }
  return {
    kind: 'python',
    port,
    pid: child.pid,
    exited: childExit(child),
    stdout: readStream(child.stdout),
    stderr: readStream(child.stderr),
    command,
    requestStop: () => {
      child.stdin!.end('shutdown\n')
    },
    forceStop: () => {
      child.kill()
    }
  }
}

async function startBun(
  port: number,
  dataDirectory: string,
  localToken: string
): Promise<ManagedBackend> {
  const command = ['bun', 'apps/backend-bun/src/main.ts'] as const
  const child = spawn(process.execPath, [resolve('apps/backend-bun/src/main.ts')], {
    cwd: resolve('apps/backend-bun'),
    env: {
      ...cleanEnvironment(),
      ADVX_BACKEND_MODE: 'production',
      ADVX_BACKEND_HOST: '127.0.0.1',
      ADVX_BACKEND_PORT: String(port),
      ADVX_DATA_DIR: dataDirectory,
      ADVX_STARTUP_TOKEN_FD: '0'
    },
    stdio: ['pipe', 'pipe', 'pipe', 'ipc']
  })
  if (
    child.pid === undefined ||
    child.stdin === null ||
    child.stdout === null ||
    child.stderr === null
  ) {
    throw new Error('Bun parity process pipes were not created')
  }
  child.stdin.end(localToken)
  return {
    kind: 'bun',
    port,
    pid: child.pid,
    exited: childExit(child),
    stdout: readStream(child.stdout),
    stderr: readStream(child.stderr),
    command,
    requestStop: () => {
      child.send({ type: 'advx.backend.shutdown', reason: 'requested' })
    },
    forceStop: () => {
      child.kill()
    }
  }
}

async function waitForHealth(backend: ManagedBackend): Promise<void> {
  const deadline = Date.now() + 15_000
  while (Date.now() < deadline) {
    try {
      const response = await fetch(`http://127.0.0.1:${backend.port}/health`, {
        headers: { authorization: `Bearer ${token}` },
        signal: AbortSignal.timeout(500)
      })
      if (response.status === 200) return
    } catch {}
    await Bun.sleep(50)
  }
  const exitCode = await Promise.race([backend.exited, Bun.sleep(0).then(() => null)])
  const details =
    exitCode === null
      ? 'process remained alive'
      : `process exited ${exitCode}: ${(await backend.stderr).trim()}`
  throw new Error(`${backend.kind} backend did not become healthy (${details})`)
}

async function stopProcess(backend: ManagedBackend): Promise<number> {
  backend.requestStop()
  return await exitBeforeDeadline(backend, 10_000)
}

async function stopIfRunning(backend: ManagedBackend | null): Promise<void> {
  if (backend === null) return
  const exited = await Promise.race([
    backend.exited.then(() => true),
    Bun.sleep(0).then(() => false)
  ])
  if (exited) return
  backend.forceStop()
  await exitBeforeDeadline(backend, 5_000).catch(() => -1)
}

async function exitBeforeDeadline(backend: ManagedBackend, deadlineMs: number): Promise<number> {
  let timeout: ReturnType<typeof setTimeout> | undefined
  try {
    return await Promise.race([
      backend.exited,
      new Promise<never>((_, reject) => {
        timeout = setTimeout(() => {
          backend.forceStop()
          reject(new Error(`${backend.kind} process did not stop before the deadline`))
        }, deadlineMs)
      })
    ])
  } finally {
    if (timeout !== undefined) clearTimeout(timeout)
  }
}

async function waitForPortRelease(port: number): Promise<boolean> {
  const deadline = Date.now() + 5_000
  while (Date.now() < deadline) {
    try {
      await fetch(`http://127.0.0.1:${port}/health`, {
        signal: AbortSignal.timeout(200)
      })
    } catch {
      return true
    }
    await Bun.sleep(50)
  }
  return false
}

async function descendantPids(rootPid: number): Promise<number[]> {
  const command = [
    'powershell',
    '-NoProfile',
    '-Command',
    'Get-CimInstance Win32_Process | Select-Object ProcessId,ParentProcessId | ConvertTo-Json -Compress'
  ]
  const child = Bun.spawn(command, { stdout: 'pipe', stderr: 'pipe' })
  const [stdout, stderr, exitCode] = await Promise.all([
    new Response(child.stdout).text(),
    new Response(child.stderr).text(),
    child.exited
  ])
  if (exitCode !== 0) throw new Error(`Process inventory failed: ${stderr.trim()}`)
  const parsed = JSON.parse(stdout) as
    | { ProcessId: number; ParentProcessId: number }
    | { ProcessId: number; ParentProcessId: number }[]
  const rows = Array.isArray(parsed) ? parsed : [parsed]
  const descendants = new Set<number>()
  let changed = true
  while (changed) {
    changed = false
    for (const row of rows) {
      if (
        !descendants.has(row.ProcessId) &&
        (row.ParentProcessId === rootPid || descendants.has(row.ParentProcessId))
      ) {
        descendants.add(row.ProcessId)
        changed = true
      }
    }
  }
  return [...descendants].sort((left, right) => left - right)
}

function processRecord(backend: ManagedBackend, exitCode: number, stdout: string, stderr: string) {
  return {
    command: backend.command.join(' '),
    exitCode,
    stdoutLineCount: nonemptyLines(stdout),
    stderrLineCount: nonemptyLines(stderr),
    stdoutSha256: sha256(stdout),
    stderrSha256: sha256(stderr)
  }
}

function cleanEnvironment(): Record<string, string> {
  return Object.fromEntries(
    Object.entries(process.env).filter(
      (entry): entry is [string, string] =>
        entry[1] !== undefined && !/^ADVX_/i.test(entry[0]) && !/_API_KEY$/i.test(entry[0])
    )
  )
}

function errorCode(body: unknown): string | null {
  const value = asRecord(body)
  if (typeof value.code === 'string') return value.code
  const detail = asRecord(value.detail)
  return typeof detail.code === 'string' ? detail.code : null
}

function eventType(message: unknown): string | null {
  const value = asRecord(message)
  if (typeof value.type === 'string') return value.type
  return typeof value.message_type === 'string' ? value.message_type : null
}

function asRecord(value: unknown): Record<string, unknown> {
  return value !== null && typeof value === 'object' ? (value as Record<string, unknown>) : {}
}

function requiredString(value: unknown, key: string, label = 'response'): string {
  const candidate = asRecord(value)[key]
  if (typeof candidate !== 'string' || candidate.length === 0) {
    throw new Error(`${label} is missing ${key}: ${JSON.stringify(value)}`)
  }
  return candidate
}

function normalizePath(path: string): string {
  return path
    .replace(/\/runtime\/sessions\/[^/]+/, '/runtime/sessions/<session-id>')
    .replace(/\/sessions\/[^/]+/, '/sessions/<session-id>')
}

function collectDiffs(expected: unknown, actual: unknown, path = '$'): Diff[] {
  if (Object.is(expected, actual)) return []
  if (
    expected === null ||
    actual === null ||
    typeof expected !== 'object' ||
    typeof actual !== 'object'
  ) {
    return [{ path, expected, actual }]
  }
  const left = expected as Record<string, unknown>
  const right = actual as Record<string, unknown>
  const keys = [...new Set([...Object.keys(left), ...Object.keys(right)])].sort()
  return keys.flatMap((key) => collectDiffs(left[key], right[key], `${path}.${key}`))
}

function sha256(value: string): string {
  return new Bun.CryptoHasher('sha256').update(value).digest('hex')
}

function nonemptyLines(value: string): number {
  return value.split(/\r?\n/).filter((line) => line.length > 0).length
}

async function freePort(): Promise<number> {
  const server = createServer()
  await new Promise<void>((resolveListen, reject) => {
    server.once('error', reject)
    server.listen(0, '127.0.0.1', resolveListen)
  })
  const address = server.address()
  if (address === null || typeof address === 'string') {
    throw new Error('Could not allocate a loopback port')
  }
  await new Promise<void>((resolveClose, reject) =>
    server.close((error) => (error === undefined ? resolveClose() : reject(error)))
  )
  return address.port
}

async function distinctFreePort(excluded: number): Promise<number> {
  for (;;) {
    const candidate = await freePort()
    if (candidate !== excluded) return candidate
  }
}

function childExit(child: ReturnType<typeof spawn>): Promise<number> {
  return new Promise((resolveExit, reject) => {
    child.once('error', reject)
    child.once('exit', (code) => resolveExit(code ?? -1))
  })
}

function readStream(stream: NodeJS.ReadableStream): Promise<string> {
  return new Promise((resolveText, reject) => {
    const chunks: Buffer[] = []
    stream.on('data', (chunk: Buffer | string) =>
      chunks.push(typeof chunk === 'string' ? Buffer.from(chunk) : chunk)
    )
    stream.once('end', () => resolveText(Buffer.concat(chunks).toString('utf8')))
    stream.once('error', reject)
  })
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path)
    return true
  } catch {
    return false
  }
}

async function removeDirectory(path: string): Promise<void> {
  let lastError: unknown
  for (let attempt = 0; attempt < 30; attempt += 1) {
    try {
      await rm(path, { recursive: true, force: true })
      return
    } catch (error) {
      lastError = error
      await Bun.sleep(100)
    }
  }
  throw lastError
}
