"""Generate the bounded synthetic CON-006 corpus with the retained Python codec."""

from __future__ import annotations

import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "apps" / "backend" / "src"))

from advx_backend.application.ports.asr import AudioSource  # noqa: E402
from advx_backend.contracts.binary import (  # noqa: E402
    BinaryEnvelopeHeader,
    BinaryInputEnvelope,
    BinaryMediaType,
    encode_binary_envelope,
)

OUTPUT = Path(__file__).with_name("fixtures") / "binary"


def fixture(
    name: str,
    *,
    version: int,
    media_type: BinaryMediaType,
    source: AudioSource | None,
    body: bytes,
    session_id: str,
    input_id: str,
    format_value: str,
    turn_id: str | None = None,
    system_audio_required: bool = False,
) -> dict[str, object]:
    header = BinaryEnvelopeHeader(
        version=version,
        media_type=media_type,
        source=source,
        session_id=session_id,
        input_id=input_id,
        captured_at_ms=1_753_980_123_456 + version,
        format=format_value,
        body_length=len(body),
        turn_id=turn_id,
        system_audio_required=system_audio_required,
    )
    payload = encode_binary_envelope(BinaryInputEnvelope(header=header, body=body))
    path = OUTPUT / f"{name}.bin"
    path.write_bytes(payload)
    return {
        "name": name,
        "file": path.name,
        "version": version,
        "mediaType": media_type.value,
        "source": None if source is None else source.value,
        "sessionId": session_id,
        "inputId": input_id,
        "capturedAtMs": header.captured_at_ms,
        "format": format_value,
        "bodyLength": len(body),
        "turnId": turn_id,
        "systemAudioRequired": system_audio_required,
        "sha256": hashlib.sha256(payload).hexdigest(),
        "byteLength": len(payload),
        "hex": payload.hex(),
    }


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    fixtures = [
        fixture("v1-audio", version=1, media_type=BinaryMediaType.AUDIO,
                source=AudioSource.MICROPHONE, body=b"\x01\x02\x03", session_id="s-v1-a",
                input_id="i-v1-a", format_value="pcm_s16le;rate=16000;channels=1"),
        fixture("v1-frame", version=1, media_type=BinaryMediaType.IMAGE,
                source=None, body=b"\xff\xd8\xff\xd9", session_id="s-v1-f",
                input_id="i-v1-f", format_value="image/jpeg"),
        fixture("v2-audio", version=2, media_type=BinaryMediaType.AUDIO,
                source=AudioSource.SYSTEM_AUDIO, body=b"\x10\x20\x30\x40", session_id="s-v2-a",
                input_id="i-v2-a", format_value="pcm_f32le;rate=48000;channels=2"),
        fixture("v2-frame", version=2, media_type=BinaryMediaType.IMAGE,
                source=None, body=b"RIFFWEBP", session_id="s-v2-f",
                input_id="i-v2-f", format_value="image/webp"),
        fixture("v3-audio", version=3, media_type=BinaryMediaType.AUDIO,
                source=AudioSource.MICROPHONE, body=b"\xaa\xbb\xcc", session_id="会话-v3",
                input_id="i-v3-a", format_value="pcm_s16le;rate=16000;channels=1",
                turn_id="turn-coordinated", system_audio_required=True),
        fixture("v3-frame", version=3, media_type=BinaryMediaType.IMAGE,
                source=None, body=b"\x89PNG\r\n\x1a\n", session_id="s-v3-f",
                input_id="i-v3-f", format_value="image/png"),
    ]
    (OUTPUT / "manifest.json").write_text(
        json.dumps(
            {"fixtures": [{key: value for key, value in item.items() if key != "hex"}
                          for item in fixtures]},
            ensure_ascii=True,
            indent=2,
        ) + "\n",
        encoding="utf-8",
    )
    (OUTPUT / "corpus.ts").write_text(
        "// Generated by ../binary-oracle.py from the retained Python codec.\n"
        "export const pythonBinaryFixtureHex = {\n"
        + "".join(f"  '{item['name']}': '{item['hex']}',\n" for item in fixtures)
        + "} as const\n",
        encoding="utf-8",
    )
    print(json.dumps({"fixtureCount": len(fixtures), "bytes": sum(f["byteLength"] for f in fixtures)}))


if __name__ == "__main__":
    main()
