export const backendBunPackage = {
  name: '@advx/backend-bun',
  runtime: 'bun',
  role: 'backend-package-foundation'
} as const

export {
  createApp,
  type AppComposition,
  type CreateAppDependencies,
  type CreateAppOptions
} from './app'
export * from './headless'
export {
  DIAGNOSTICS_ARTIFACT_KINDS,
  DIAGNOSTICS_BUNDLE_DEFAULT_MAX_FILE_BYTES,
  DIAGNOSTICS_BUNDLE_DEFAULT_MAX_TOTAL_BYTES,
  DIAGNOSTICS_BUNDLE_MAX_FILES,
  DIAGNOSTICS_BUNDLE_SCHEMA_VERSION,
  DiagnosticsBundleError,
  createDiagnosticsBundle,
  createRuntimeVersionSnapshot,
  type DiagnosticsArtifactKind,
  type DiagnosticsBundleErrorCode,
  type DiagnosticsBundleFile,
  type DiagnosticsBundleInput,
  type DiagnosticsBundleManifest,
  type DiagnosticsBundleResult,
  type DiagnosticsFileSource,
  type DiagnosticsJsonSource,
  type DiagnosticsMissingArtifact,
  type RuntimeVersionSnapshotInput
} from './infrastructure'
export {
  BUN_PROFILE_MAX_DURATION_MS,
  BUN_PROFILE_MIN_DURATION_MS,
  BUN_PROFILE_SCHEMA_VERSION,
  BUN_PROFILE_STOP_GRACE_MS,
  BunProfileError,
  createBunProfileInvocation,
  runBunProfile,
  type BunProfileErrorCode,
  type BunProfileInvocation,
  type BunProfileKind,
  type BunProfileResult,
  type BunProfileRunOptions,
  RUNTIME_PROFILE_MAX_DURATION_MS,
  RUNTIME_PROFILE_MAX_INTERVAL_MS,
  RUNTIME_PROFILE_MAX_SAMPLES,
  RUNTIME_PROFILE_MIN_DURATION_MS,
  RUNTIME_PROFILE_MIN_INTERVAL_MS,
  RUNTIME_PROFILE_SCHEMA_VERSION,
  RuntimeProfileError,
  collectRuntimeProfile,
  createRuntimeProfileSample,
  type RuntimeCpuUsage,
  type RuntimeMemoryUsage,
  type RuntimeProfileErrorCode,
  type RuntimeProfileOptions,
  type RuntimeProfileResult,
  type RuntimeProfileSample
} from './infrastructure'
export {
  BackendApplication,
  BackendApplicationError,
  type ApplicationEvent,
  type AsrProviderEvent,
  type AsrProvider,
  AsrTurnCoordinator,
  type AsrObservation,
  type AsrRuntimeSink,
  type AsrScheduler,
  type AsrTimerHandle,
  type AsrRequest,
  type AsrTranscript,
  type CoordinatedAsrTranscript,
  type AudioFormat,
  type AudioSource,
  type BackendProfileReader,
  type CancellationReason,
  type CancellationReasonCode,
  type DurationMs,
  type EventPublisher,
  type IdGenerator,
  type LogEvent,
  type LogSink,
  modelUsage,
  type ModelFinishReason,
  type ModelGenerationOutput,
  type ModelGenerationPurpose,
  type ModelGenerationRequest,
  type ModelGenerationResult,
  type ModelInputPart,
  type ModelMessage,
  type ModelMessageRole,
  type ModelOutputRequest,
  ModelOutputValidationService,
  type ModelOutputValidationDependencies,
  ModelRequestScheduler,
  ModelRoomMemoryExtractor,
  ModelRoomMemoryExtractorError,
  ROOM_MEMORY_EXTRACTION_SCHEMA_NAME,
  ROOM_MEMORY_EXTRACTION_MAX_CANDIDATES,
  ROOM_MEMORY_EXTRACTION_TIMEOUT_MS,
  ROOM_MEMORY_EXTRACTION_MAX_OUTPUT_TOKENS,
  DEFAULT_MODEL_SCHEDULING_POLICY,
  createModelSchedulingPolicy,
  type ModelRequestSchedulerDependencies,
  type ModelRoomMemoryExtractorDependencies,
  ReplayService,
  ReplayServiceError,
  AGENT_EVAL_ASSERTION_IDS,
  AGENT_EVAL_SCHEMA_VERSION,
  AgentEvalFixtureError,
  evaluateAgentFixture,
  parseAgentEvalFixture,
  serializeAgentEvalReport,
  type LiveReplayEvidence,
  type LiveReplayProvider,
  type RecordedReplayRunContext,
  type RecordedReplayRunner,
  type ReplayServiceErrorCode,
  type ReplayServiceOptions,
  type AgentEvalAssertion,
  type AgentEvalAssertionId,
  type AgentEvalCall,
  type AgentEvalFixture,
  type AgentEvalObservation,
  type AgentEvalOutput,
  type AgentEvalPrivacyClassification,
  type AgentEvalProviderEvidenceClass,
  type AgentEvalReport,
  type RoomMemoryExtractionScope,
  type RoomMemoryExtractionInput,
  type ExtractedRoomMemoryCandidate,
  type RoomMemoryExtractorPort,
  type ModelSchedulerQueue,
  type ModelSchedulerQueueFactory,
  type ModelSchedulerQueueOptions,
  type ModelSchedulerQueueTaskOptions,
  type ModelSchedulerSnapshot,
  type ModelSchedulingPolicy,
  type ModelSchedulingPolicyInput,
  type ModelSchedulingResult,
  type ModelSchedulingStatus,
  type ModelSchedulingTrigger,
  ObservationWaveService,
  SessionAudienceService,
  SessionAudienceError,
  MIN_SESSION_VIEWERS,
  MAX_ACTIVE_SESSION_VIEWERS,
  MAX_CREATED_SESSION_VIEWERS,
  type SessionAudienceCreateInput,
  type SessionAudienceDependencies,
  type SessionAudienceErrorCode,
  type SessionAudienceReconciliation,
  type SessionAudienceRestoreInput,
  type ViewerPrivateStateCommit,
  type ViewerReplacement,
  type ViewerSequenceFence,
  ViewerCandidateSelector,
  ViewerCandidateSelectionError,
  USER_CANDIDATE_BUDGET,
  AMBIENT_CANDIDATE_BUDGET,
  DIRECT_MENTION_CANDIDATE_BUDGET,
  SCREEN_ACTIVE_VIEWER_DIVISOR,
  type ViewerCandidateBudgetKind,
  type ViewerCandidateSelection,
  type ViewerCandidateSelectionErrorCode,
  type ViewerCandidateSelectionInput,
  ViewerDecisionContextBuilder,
  ViewerDecisionContextError,
  VIEWER_PUBLIC_SOURCE_QUOTA,
  VIEWER_MEMORY_SLICE_LIMIT,
  VIEWER_ACTIVE_ID_LIMIT,
  type NormalizedViewerMention,
  type ViewerDecisionContext,
  type ViewerDecisionContextErrorCode,
  type ViewerDecisionContextInput,
  type ViewerDecisionFence,
  type ViewerDecisionPolicy,
  type ViewerMentionMetadata,
  type ViewerPersonaContext,
  type ViewerPrivateContext,
  ViewerGenerationService,
  ViewerGenerationError,
  VIEWER_BATCH_INTERVAL_MS,
  VIEWER_GENERATION_MAX_OUTPUT_TOKENS,
  buildViewerGenerationRequest,
  type AcceptedViewerBarragePublication,
  type PublishedViewerBarrage,
  type ViewerBarrageAcceptancePort,
  type ViewerBarragePublicationCommit,
  type ViewerBarragePublicationPort,
  type ViewerFrameLoader,
  type ViewerGenerationAcceptanceInput,
  type ViewerGenerationDependencies,
  type ViewerGenerationInput,
  type ViewerGenerationOutcome,
  type ViewerGenerationOutcomeStatus,
  BarragePipeline,
  BarragePipelineError,
  BARRAGE_DUPLICATE_WINDOW_MS,
  BARRAGE_DENSITY_WINDOW_MS,
  BARRAGE_MAX_PUBLICATIONS_PER_DENSITY_WINDOW,
  BARRAGE_MAX_DUPLICATE_ENTRIES,
  BARRAGE_SEMANTIC_DUPLICATE_THRESHOLD,
  BARRAGE_PERSONAL_COOLDOWN_FLOOR_MS,
  BARRAGE_FATIGUE_INCREMENT,
  BARRAGE_ENGAGEMENT_INCREMENT,
  BARRAGE_PEER_AFFINITY_INCREMENT,
  createBarragePipelinePolicy,
  barrageAtomicRejection,
  applyBarrageViewerStateEffect,
  normalizeBarrageSemanticText,
  isSemanticBarrageDuplicate,
  type BarragePipelinePolicyInput,
  type BarragePipelinePolicy,
  type BarragePipelineViewerSnapshot,
  type TrustedViewerBarrageEvent,
  type RecentBarragePublication,
  type BarragePipelineSnapshot,
  type BarrageViewerStateEffect,
  type BarrageAtomicPublicationCommand,
  type BarrageRejectionReason,
  type BarrageAtomicPublicationResult,
  type BarragePublicationStatePort,
  type BarragePipelineDependencies,
  type AcceptedBarrageSideEffectSubmission,
  type AcceptedBarrageSideEffectPort,
  SharedBrainSideEffectService,
  SHARED_BRAIN_MAX_OUTSTANDING_EXTRACTIONS,
  MODE_MEME_DECAY_FACTOR,
  MODE_MEME_ARCHIVE_AFTER_MS,
  MODE_MEME_ARCHIVE_MAX_USES,
  type SharedBrainSessionFence,
  type ModeMemeProvenancePort,
  type ModeMemeProposalResult,
  type SharedBrainSideEffectFailure,
  type SharedBrainSideEffectSnapshot,
  type SharedBrainSideEffectDependencies,
  OBSERVATION_MERGE_WINDOW_MS,
  OBSERVATION_REQUEST_TTL_MS,
  OBSERVATION_PUBLIC_WINDOW_MS,
  OBSERVATION_PUBLIC_LIMIT,
  OBSERVATION_REPLY_WINDOW_MS,
  OBSERVATION_REPLY_LIMIT,
  FRAME_TIMELINE_WINDOW_MS,
  DIRECT_FRAME_WINDOW_MS,
  FRAME_SIMILARITY_THRESHOLD,
  FRAME_SEGMENT_ANCHOR_MS,
  FRAME_BUNDLE_LIMIT,
  SCREEN_CHANGE_THRESHOLD,
  SCREEN_TRIGGER_COOLDOWN_MS,
  observationTriggerPriority,
  selectObservationFrames,
  type FrozenObservationContext,
  type ObservationContextReader,
  type ObservationEventSource,
  type ObservationFrame,
  type ObservationFrameBundle,
  type ObservationFrameBundleItem,
  type ObservationInputEvent,
  type ObservationMemoryReader,
  type ObservationSubmission,
  type ObservationSubmissionStatus,
  type ObservationTriggerEvent,
  type ObservationVisualMode,
  type ObservationWave,
  type ObservationWaveDependencies,
  type ObservationWaveOptions,
  type ScheduledModelAttempt,
  type ScheduledModelTask,
  type ModelProvider,
  type ModelRequestBudget,
  createModelRequestBudget,
  type ModelRole,
  type ModelStreamEvent,
  type ModelUsage,
  type ValidatedViewerGeneration,
  type ViewerOutputFence,
  type MonotonicClock,
  type MonotonicDeadline,
  type MonotonicTimestampMs,
  type ProcessShutdownNotifier,
  BACKEND_PROCESS_EXIT_CODES,
  type BackendProcessExitCode,
  type BackendProcessControlMessage,
  type BackendProcessHost,
  type BackendProcessLifecycleResult,
  type BackendProcessSignal,
  type BackendProcessStopReason,
  type ProcessCleanupStep,
  ProcessLifecycleSupervisor,
  type ProcessLifecycleResources,
  type DatabaseLifecycleResource,
  type FlushableLifecycleResource,
  type ProviderCallContext,
  type ProviderCapability,
  type ProviderCapabilityCheck,
  type ProviderCapabilityProbeRequest,
  type ProviderCapabilityProbeResult,
  type ProviderControlPort,
  type ProviderErrorCode,
  type ProviderErrorSource,
  type ProviderFailure,
  type ProviderFailureInput,
  providerFailure,
  type ProviderHealthRequest,
  type ProviderHealthResult,
  type ProviderHealthStatus,
  type ProviderIdentity,
  type ProviderKind,
  type ProviderLatency,
  type ProviderOutcome,
  type ProviderProbeStatus,
  type ProviderRevision,
  providerRevision,
  type ProviderRole,
  type ProviderRoleModel,
  type ProtocolRepairAttempt,
  protocolRepairAttempt,
  DEFAULT_DESKTOP_CLIENT_ID,
  type ObservationWaveBoundary,
  REALTIME_CLOSE,
  RealtimeHub,
  type RealtimeHubOptions,
  type RealtimeHubSnapshot,
  type RealtimeOpenInput,
  type RealtimePublicationResult,
  type RealtimePublisher,
  type RealtimeSessionReader,
  type RealtimeSocketPort,
  type RealtimeWireFamily,
  type RoomRecord,
  type RoomEventContextQuery,
  type RoomEventContextWindow,
  type RoomEventInput,
  type RoomEventPayload,
  type RoomEventRecord,
  type RoomEventRepository,
  type RoomEventRetentionPolicy,
  type RoomEventRetentionRule,
  type RoomMemoryCandidate,
  type RoomMemoryCommitResult,
  type RoomMemoryEdit,
  type RoomMemoryEvidence,
  type RoomMemoryMerge,
  type RoomMemoryRecord,
  type RoomMemoryReplacement,
  type RoomMemoryRepository,
  type RoomMemorySlice,
  type RoomMemorySliceQuery,
  type RoomMemoryState,
  type RoomMemoryType,
  type MemeCandidateOutcome,
  type ModeMemeAction,
  type ModeMemeAutoIngestSetting,
  type ModeMemeCandidate,
  type ModeMemeCommitResult,
  type ModeMemeEdit,
  type ModeMemeEvent,
  type ModeMemePinUpdate,
  type ModeMemeRecord,
  type ModeMemeRepository,
  type ModeMemeSource,
  type ModeMemeState,
  type ModeMemeStateChange,
  type ModeMemeUse,
  type DurableOutboxClaim,
  type DurableOutboxEnqueue,
  type DurableOutboxFence,
  type DurableOutboxFenceKind,
  type DurableOutboxKind,
  type DurableOutboxLeaseIdentity,
  type DurableOutboxRecord,
  type DurableOutboxRetry,
  type DurableOutboxSettlement,
  type DurableOutboxStatus,
  type OutboxRepository,
  type RoomRepository,
  type PersistedRoomState,
  type PersistedSessionState,
  RoomSessionLifecycle,
  RoomSessionLifecycleError,
  type RoomSessionLifecycleDependencies,
  type RoomSessionLifecycleErrorCode,
  RuntimeControlError,
  RuntimeControlService,
  type RuntimeControlErrorCode,
  type RuntimeControlKernel,
  type RuntimeControlKernelFactory,
  type RuntimeControlOperations,
  type RuntimeControlRecoveryCommit,
  type RuntimeSessionStartRequest,
  type LifecycleCommandIdentity,
  type MarkFailedCommand,
  type RuntimeReplacementCommit,
  type RuntimeReplacementReason,
  type StartSessionCommand,
  type RuntimeSpecApplyCommand,
  type RuntimeSpecApplyIdentity,
  type RuntimeSpecCapabilityGate,
  type RuntimeSpecCommitToken,
  RuntimeSpecCoordinator,
  RuntimeSpecCoordinatorError,
  type RuntimeSpecCoordinatorDependencies,
  type RuntimeSpecCoordinatorErrorCode,
  type RuntimeSpecRecord,
  type RuntimeSpecRepository,
  type RuntimeSpecRevisionStatus,
  type RuntimeSpecRollbackCommand,
  type RuntimeSpecWorkFence,
  type ScopedTask,
  type SessionRecord,
  type SessionRepository,
  type SessionResourceIdentity,
  type SessionResources,
  type ShutdownNotice,
  type ShutdownReason,
  type ShutdownReceipt,
  type TaskCancellation,
  type TaskExecutionContext,
  type TaskHandle,
  type TaskScope,
  type TraceCorrelation,
  type TraceEvent,
  type TraceSink,
  type TraceStatus,
  type TransactionBoundary,
  type TransactionContext,
  type WallClock,
  type WallClockTimestampMs,
  durationMs,
  monotonicDeadline,
  monotonicTimestampMs,
  transactionContext,
  wallClockTimestampMs
} from './application'
export {
  DualChannelAsr,
  AiSdkModelGateway,
  StepFunAsrProvider,
  DeterministicAsrProvider,
  DeterministicModelProvider,
  RecordedAsrProvider,
  RecordedModelProvider,
  type AsrAudioChunk,
  type AsrChannelPhase,
  type AsrChannelStatus,
  type DualChannelAsrConfig,
  type DualChannelAsrDependencies,
  type ModelGatewayConfig,
  type ModelGatewayDependencies,
  type ModelGatewayFetch,
  type StepFunAsrConfig,
  type StepFunAsrProviderDependencies,
  type StepFunFetch,
  type DeterministicAsrConfig,
  type DeterministicAsrPlan,
  type DeterministicModelConfig,
  type DeterministicModelPlan,
  type RecordedAsrConfig,
  type RecordedAsrEvent,
  type RecordedAsrFixture,
  type RecordedModelConfig,
  type RecordedModelFixture,
  type RecordedModelResponse,
  type ProviderAdapterControls,
  type ProviderEvidenceClass,
  type ProviderEvidenceMetadata,
  type ProviderEvidenceSource
} from './providers'
export {
  type BackendProfile,
  type RoomSessionLifecycleReason,
  type RoomSessionLifecycleState,
  type RoomSessionSnapshot,
  type RuntimeSpecDiffSummary,
  type RuntimeSpecIdentityDiff,
  summarizeRuntimeSpecDiff
} from './domain'
export {
  ADVX_SQLITE_MIGRATIONS,
  ADVX_SQLITE_BUSY_TIMEOUT_MS,
  ADVX_SQLITE_DATABASE_FILENAME,
  AdvxSqliteDatabase,
  AdvxSqliteDatabaseError,
  classifySqliteFault,
  BACKEND_CONFIG_DEFAULTS,
  BackendConfigError,
  DIAGNOSTIC_EVENT_NAMES,
  createTransientTaskScope,
  createDiagnosticLogger,
  isVersionedDiagnosticEventName,
  sanitizeDiagnosticValue,
  SqliteModeMemeRepository,
  SqliteOutboxRepository,
  LEGACY_ALEMBIC_HEAD,
  LEGACY_MIGRATION_BASELINE_VERSION,
  LEGACY_MIGRATION_STRATEGY,
  LegacyDatabaseMigrationError,
  PythonOnlineBackupError,
  PythonSqliteOnlineBackupAdapter,
  SqlitePersistenceError,
  SqliteRoomEventRepository,
  SqliteRoomMemoryRepository,
  SqliteRoomRepository,
  SqliteRuntimeSpecRepository,
  SqliteSessionRepository,
  SqliteTransactionBoundary,
  advxPersistenceSchema,
  createSqliteRepositories,
  createTemporaryAdvxSqliteDatabase,
  createModelRequestScheduler,
  createPQueueModelSchedulerQueue,
  createRoomEventRecord,
  legacyMigrationRunDirectory,
  migrateLegacyDatabase,
  modeMemeCandidates,
  modeMemeEvents,
  modeMemeSettings,
  modeMemes,
  durableOutbox,
  parseBackendConfig,
  rooms,
  roomEvents,
  roomLongTermMemories,
  roomMemoryCandidates,
  roomMemoryEvidence,
  roomMemoryHeads,
  runWithSqliteFaultStatus,
  sessionRecords,
  sessionRuntimeRevisions,
  sqliteCrashRecoveryStatus,
  type AdvxSqliteCheckpoint,
  type AdvxSqliteDatabaseOptions,
  type AdvxSqliteDatabaseErrorCode,
  type AdvxSqliteDatabaseHealth,
  type AdvxSqliteOpenMode,
  type BackendConfig,
  type BackendMode,
  type DiagnosticEnvelope,
  type DiagnosticEventInput,
  type DiagnosticEventName,
  type DiagnosticLevel,
  type DiagnosticLogger,
  type DiagnosticLoggerOptions,
  type DiagnosticOutcome,
  type DiagnosticProcess,
  type DiagnosticSource,
  type LogLevel,
  type ProviderProfile,
  type SqlitePersistenceErrorCode,
  type SqliteCommitState,
  type SqliteFaultContext,
  type SqliteFaultDisposition,
  type SqliteFaultKind,
  type SqliteFaultOperation,
  type SqliteFaultResult,
  type SqliteFaultStatus,
  type SqliteRepositories,
  type BackendStopReceipt,
  type LegacyBackupRestoreAdapter,
  type LegacyDatabaseMigrationErrorCode,
  type LegacyDatabaseMigrationOptions,
  type LegacyDatabaseMigrationReceipt,
  type LegacyTableComparison,
  type OnlineRestoreReceipt,
  type PythonOnlineBackupAdapterOptions,
  type PythonOnlineBackupErrorCode,
  type PQueueModelRequestSchedulerDependencies,
  type TemporaryAdvxSqliteDatabase
} from './infrastructure'
export {
  createProcessApp,
  startProcessApp,
  type RunningProcessApp,
  type StartProcessAppOptions
} from './main'

export {
  ADVX_OPENAPI_SNAPSHOT_PATH,
  ADVX_OPENAPI_VERSION,
  createAdvxOpenApiDocument,
  serializeAdvxOpenApiDocument,
  type AdvxOpenApiDocument
} from './openapi/document'
export {
  createContractDocumentationApp,
  type DocumentationAppOptions
} from './openapi/app'
